export enum contentRating{
    U='U',
    UA7Plus = 'U/A 7+',
    UA13Plus = 'U/A 13+',
    UA16Plus = 'U/A 16+',
    EighteenPlus = '18+',
}

export enum Language {
    English = 'English',
    Hindi = 'Hindi',
    Tamil = 'Tamil',
    Telugu = 'Telugu',
    Kannada = 'Kannada',
    Malayalam = 'Malayalam',
    Bengali = 'Bengali',
    Marathi = 'Marathi',
    Gujarati = 'Gujarati',
    Punjabi = 'Punjabi',
    Urdu = 'Urdu',
    Spanish = 'Spanish',
    French = 'French',
    German = 'German',
    Chinese = 'Chinese',
    Japanese = 'Japanese',
    Korean = 'Korean',
    Arabic = 'Arabic',
    Russian = 'Russian',
  }

export enum Genre {
    Action = 'Action',
    Adventure = 'Adventure',
    AnimalsAndNature = 'Animals and Nature',
    Anime = 'Anime',
    Art = 'Art',
    Awards = 'Awards',
    Biopic = 'Biopic',
    Crime = 'Crime',
    DevotionalAndSpiritual = 'Devotional & Spiritual',
    Documentary = 'Documentary',
    Drama = 'Drama',
    FairyTales = 'Fairy Tales',
    Family = 'Family',
    Food = 'Food',
    History = 'History',
    Historical = 'Historical',
    Horror = 'Horror',
    Kids = 'Kids',
    Lifestyle = 'Lifestyle',
    Musical = 'Musical',
    Mythology = 'Mythology',
    Mystery = 'Mystery',
    Parenting = 'Parenting',
    Patriotic = 'Patriotic',
    Philosophy = 'Philosophy',
    Reality = 'Reality',
    Romance = 'Romance',
    RomCom = 'Rom-Com',
    ScienceAndTechnology = 'Science & Technology',
    ScienceFiction = 'Science Fiction',
    Superhero = 'Superhero',
    TalkShow = 'Talk Show',
    Thriller = 'Thriller',
    Travel = 'Travel'
}
